export const authTypes = {
    LOGIN_REQUEST: "LOGIN_REQUEST",
    LOGIN_REJECTED: "LOGIN_REJECTED",
    LOGIN_FULFILLED: "LOGIN_FULFILLED",

    LOGIN_PASSWORD_REQUEST: "LOGIN_PASSWORD_REQUEST",
    LOGIN_PASSWORD_REJECTED: "LOGIN_PASSWORD_REJECTED",
    LOGIN_PASSWORD_FULFILLED: "LOGIN_PASSWORD_FULFILLED",

    AUTHENTICATE: "AUTHENTICATE",
    AUTHENTICATE_REJECTED: "AUTHENTICATE_REJECTED",
    AUTHENTICATE_FULFILLED: "AUTHENTICATE_FULFILLED",

    LOGOUT: "LOGOUT",
    LOGOUT_REJECTED: "LOGOUT_REJECTED",
    LOGOUT_FULFILLED: "LOGOUT_FULFILLED",
};
